version: '3'
services:
  ruby:
    image: ruby:2.5
    build:
      context: ../../../
      dockerfile: dev/docker/ruby2.5/anonymizer/Dockerfile
    volumes:
      - "../../../:/usr/src/anonymizer"
    depends_on:
      - mysql
    command: ['bash', '-c', 'bundle install --deployment; sleep 60000']
  mysql:
    image: mysql:8
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: anonymizer
      MYSQL_USER: anonymizer
      MYSQL_PASSWORD: anonymizer
      MYSQL_ROOT_PASSWORD: anonymizer
    command: --default-authentication-plugin=mysql_native_password
